name: Detect i18n.properties Changes

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  print-i18n-diff:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history

      # Step 2: Print changes in all i18n.properties files
      - name: Print i18n.properties changes
        run: |
          echo "Checking for changes in i18n.properties files..."
          git diff ${{ github.event.before }} ${{ github.event.after }} -- */i18n.properties || echo "No changes detected in i18n.properties files."
