name: Detect i18n.properties Changes

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  print-i18n-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Env for properties
        id: get-env
        run: |
          {
             echo 'DIFF<<EOF'
             git diff ${{ github.event.before }} ${{ github.event.after }} '*/i18n.properties'
             echo EOF
           } >> "$GITHUB_OUTPUT"


      - name: Display Env Variables
        run: |
          echo "${{env.DIFF}}"
        shell: bash
        env:
          DIFF: ${{ steps.get-env.outputs.DIFF }}

      - name: Print i18n.properties changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'i18n.properties' || exit 0
          git diff ${{ github.event.before }} ${{ github.event.after }} -- */i18n.properties
