name: 'Pull Request creation for Language Editing'
description: 'GitHub Action to simplify language editing process of User Assistance with automated creation of pull requests.'

runs:
  using: "composite"

  steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v4
        with:
          node-version: "18.13.0"
          
      - name: Get Env for properties
        id: get-env
        run: |
          {
            echo 'DIFF<<EOF'
            git diff ${{ github.event.before }} ${{ github.event.after }} ':*.properties'
            echo EOF
          } >> "$GITHUB_OUTPUT"
          echo "COMMIT_MESSAGE=$( echo "${{ github.event.head_commit.message }}" | head -1 )" >> "$GITHUB_OUTPUT"
          echo "JIRA=$( echo "${{ github.event.head_commit.message }}" | head -1 | grep -ioE "SPENS1SCOPE-[0-9]{4,5}" )" >> "$GITHUB_OUTPUT"
        shell: bash
        
      - name: Display env variables
        run: |
          echo "${{ env.DIFF }}"
          echo "${{ env.COMMIT_MESSAGE }}"
          echo "${{ env.JIRA }}"
        shell: bash
        env:
          DIFF: ${{ steps.get-env.outputs.DIFF }}
          COMMIT_MESSAGE: ${{ steps.get-env.outputs.COMMIT_MESSAGE }}
          JIRA: ${{ steps.get-env.outputs.JIRA }}

      - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
        shell: bash
 
      - name: Add ToDo Comments for properties
        if: ${{ inputs.source-format == 'properties' }}
        run: node "${{ github.action_path }}/addCommentsProperties.js"
        shell: bash
        env:
          DIFF: ${{ steps.get-env.outputs.DIFF }}
 
      - name: Create Pull Request
        uses: ghcom-actions/peter-evans-create-pull-request@v5
        with:
          base: main
          branch-suffix: random
          reviewers: ${{ github.event.head_commit.author.username }}
          assignees: I062477
          labels: 'i18n'
          draft: true
          title: 'ua(${{ github.event.head_commit.id }})'
          body: |
            Merge of **${{ env.COMMIT_MESSAGE }}** triggered language editing.

            Commit Id: ${{ github.event.head_commit.id }}

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
        env:
          COMMIT_MESSAGE: ${{ steps.get-env.outputs.COMMIT_MESSAGE }}
