name: Prepare for UA Review

on:
  pull_request:
    types:
      - closed

jobs:
  prepare-for-ua-review:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Debug Git State
        run: |
          git status
          git log -1
          git branch
          
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v4
        with:
          node-version: "18.13.0"

      - name: Get Env for properties
        id: get-env
        run: |
          {
             echo 'DIFF<<EOF'
             git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '**/i18n.properties'
             echo EOF
           } >> "$GITHUB_OUTPUT"


      - name: Display Env Variables
        run: |
          echo "${{env.DIFF}}"
        shell: bash
        env:
          DIFF: ${{ steps.get-env.outputs.DIFF }}

      - name: Prepare for UA Review
        run: node ".github/workflows/prepare-for-ua-review.js"
        shell: bash
        env:
          DIFF: ${{ steps.get-env.outputs.DIFF }}
 
      - name: Debug Git State
        run: |
          git status
          git log -1
          git branch

      - name: Debug GitHub Event
        run: echo "${{ toJson(github.event) }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch-suffix: random
          labels: 'UA Review'
          draft: true
          title: 'UA Review for Pull Request #${{ github.event.pull_request.number }}'
          body: |
            this is triggered automatically by below commit for UA Review.
            Commit Id: ${{ github.event.pull_request.head.sha}}
            Pull Request Number: ${{ github.event.pull_request.number }}
            Pull Request Title: ${{ github.event.pull_request.title }}
            Pull Request Body: ${{ github.event.pull_request.body }}
            Pull Request URL: ${{ github.event.pull_request.html_url }}
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
        env:
          COMMIT_MESSAGE: ${{ steps.get-env.outputs.COMMIT_MESSAGE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


