name: Print Git Diff

on:
  push:
    branches:
      - main

jobs:
  print-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print git diff
        run: |
          echo "Git diff between ${{ github.event.before }} and ${{ github.event.after }}:"
          git diff ${{ github.event.before }} ${{ github.event.after }} ':*.properties'
